#!/bin/sh

bspc config top_padding          0
bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio             0.5
bspc config single_monocle          false
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   false
bspc config pointer_follows_monitor true

# nord
bspc config normal_border_color     "#665c54"
bspc config presel_feedback_color   "#3c3836"
bspc config focused_border_color    "#d65d0e"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a main state=floating
bspc rule -a client state=floating
bspc rule -a kruler state=floating border=off center=on
bspc rule -a floating state=floating center=on

