#! /bin/sh

bspc config top_padding          0
bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio             0.5
bspc config single_monocle          false 
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config click_to_focus          true
bspc config pointer_follows_monitor true

# nord
bspc config normal_border_color		"#2f383e"
bspc config presel_feedback_color	"#a7c080"
bspc config focused_border_color	"#a7c080"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc rule -a "Firefox Beta" state=tiled
bspc rule -a main state=floating
bspc rule -a kruler state=floating border=off center=on
bspc rule -a floating state=floating center=on
